services:
  mysql:
    container_name: mysql
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: msvc_users
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring

  postgre:
    container_name: postgre
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: root1234
      POSTGRES_DB: msvc_courses
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  msvc-users:
    container_name: msvc-users
    build:
      context: ./
      dockerfile: ./msvc-ususers/Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./msvc-ususers/.env
    networks:
      - spring
    depends_on:
      - mysql
    restart: on-failure

  msvc-courses:
    container_name: msvc-courses
    build:
      context: ./
      dockerfile: ./msvc-courses/Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ./msvc-courses/.env
    networks:
      - spring
    depends_on:
      - postgre
      - msvc-users
    restart: always

volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres

networks:
  spring:
